[artifact]
folder = "build/libs"
pattern = "lets-do-photographers-#.jar"
game_versions = ["1.20.1"]
loaders = ["fabric", "quilt"]

[changelog]
type = "editor"

[modrinth]
id = "modrinth project id"
featured = true

[[modrinth.dependencies]]
id = "P7dR8mSH"
dependency_type = "required"

[[modrinth.dependencies]]
id = "P7dR8mSH"
dependency_type = "required"

[github]
repo = ["user", "repo"]
draft = true
